---
title: "About Me"
type: "about"
---

### Who am I? 
I am a Master student of Statistics at UC Davis. I guess you are here because you want to know a bit about me, huh? My interests include statistics, data analysis, data science and machine learning. This website is the home of my data projects and tutorials. Also I'm happy to share what I've learned so far. My ultimate goal is to contribute my personal skills and experience to the technology and community.

I'm looking for data analyst and data scientist jobs. Any help will be appreciated! Looking forward to hearing from you if you have any questions or suggestions.

### Education

* MS in Statistics, University of California, America
* BS in Mathematics and Applied Mathematics, Jilin University, China
* BS in Economics (Minor), Jilin University, China 


### Skills & Interests in Data Science

Studing applied mathematics and statistics for 6 years, I have taken courses including Machine Learning, Statistical Computing, Categorical Data Analysis, Algorithm Design and so on. I am comfortable working with R, Python, SQL programming languages, and also experienced in using data visualization tools like Tableau and R-shiny. I have been extensively involved in working in the field of data as part of my academic projects and internships. My multiple practical experience gave me the experience and confidence to develop solutions to complex analytic challenges and real-world problems.

How can we learn from data? As an enthusiast of data science, I am motivated by the belief that data can be used to make better decisions. I am interested in exploring various facets of data science. Now I am focus on maching learning and information visualization to augment my professional experience. I will keep learning and practicing in the future, using data to inform decisions that positively affect user experience for companies. 

